### ISSUE TITLE
Epic: caBLE authenticator support

### ISSUE THREAD

**Issue by micolous** [kanidm/webauthn-rs#259]
This is to track work and ideas relating to supporting caBLE authenticators (aka: authenticator on your mobile device), and acting as a caBLE authenticator.

## In review

* #232 (MVP)

## Future work ideas

Not a commitment to deliver it, and not in any particular order:

* [ ] Support Pairing / Linking / "Remember Device" (Android + Chrome).
* [ ] Write a tunnel server
* [ ] DevicePubKey extension (Android + Chrome). You can have the authenticator device attest its identity and give out a SafetyNet attestation.
* [ ] Figure out how to use Apple's tunnel server (if possible)
* [ ] Use bluez Rust bindings to send advertisements on Linux, rather than needing a serial Bluetooth HCI controller
* [ ] Port to some embedded system

**Comment by Firstyear** [comment]
I'm not sure DPK is worth supporting at this point as previously discussed.

**Comment by micolous** [comment]
FIDO Alliance recently published a review draft of the CTAP 2.2 specification, which [includes a caBLE specification][0].  Some observations:

* The protocol for an authenticator establishing a connection to a tunnel server is considered "a private detail of the authenticator's implementation".

  As a result, I've dropped supporting Apple's tunnel server as an authenticator from the list, because `webauthn-authenticator-rs` (and our `cable-tunnel-server`) implements Chromium's protocol, and I presume Apple will do something different here.

* Chromium differs from the spec in many ways, which would make it incompatible. I'm otherwise pretty confident that `webauthn-authenticator-rs` implements the protocol correctly-enough.

* The major gap for `webauthn-authenticator-rs` is implementing pairing ([state-assisted transactions][1]); though I think only Android implements it.
 
  From the looks of it, the dependency on Firebase Cloud Messaging would make it difficult to implement an authenticator using a non-first-party tunnel server, and also makes implementing pairing on our `cable-tunnel-server` somewhat complicated.

[0]: https://fidoalliance.org/specs/fido-v2.2-rd-20230321/fido-client-to-authenticator-protocol-v2.2-rd-20230321.html#sctn-hybrid
[1]: https://fidoalliance.org/specs/fido-v2.2-rd-20230321/fido-client-to-authenticator-protocol-v2.2-rd-20230321.html#hybrid-state-assisted

**Comment by Firstyear** [comment]
I think for the moment that what we have is a really good demonstration of what's possible, especially for other libraries like the webauthn portal library, but until there is more demand outside of testing and smaller use cases we probably don't want to stress about details like pairing :)

**Comment by micolous** [comment]
The main issue with pairing is that the library would need a place to store some state (the contact list), and interfaces to manipulate it. This would make things more complicated for an application using `webauthn-authenticator-rs`.

AFAICT only Android supports pairing, and I'd like to see another implementation before going down that rabbit hole.  However, I don't know if Apple will even bother with that, given that the Apple ecosystem solution is that applications use their platform WebAuthn APIs to access the iCloud Keychain.

**Comment by AlfioEmanueleFresta** [comment]
I'd like to try and pick up the work on State-assisted Transactions (STs). I believe [hybrid transport is crucial to unlock Passkey adoption across platforms](https://alfioemanuele.io/dev/2024/01/31/a-vision-for-passkeys-on-the-linux-desktop.html#prioritizing-passkey-support), and STs are highly desirable for our use case. 

As @micolous pointed out, this requires storing authenticator information. I propose applications wanting to use state-assisted transactions should provide storage, by means of optionally providing an implementation of a storage-provider interface. For example, it would be the responsibility of the Linux FIDO2 portal to store known devices, and the security properties of this storage may be adapted depending on the use case - eg. using the TPM to bind the state to a specific device.

**Comment by vellotis** [comment]
I’m a bit hesitant to ask, but are you aware that the caBLE v2 authenticator code was part of the Chromium public repository?

MR: https://github.com/chromium/chromium/commit/a677f381376f62a85254233be0821d9f816e6aca

**Comment by Firstyear** [comment]
Yes we know that code exists? Why bring it up though?

**Comment by vellotis** [comment]
I first thought, that maybe it hasn't been discovered yet. But I later regretted my question as I understood from reading the other comments and from the `webauthn-authenticator-rs` example implementation that it has been already considered.

Pardon!

**Comment by micolous** [comment]
Yeah, `webauthn-authenticator-rs` is based on Chromium's implementation, because it was written before there was an official spec (FIDO 2.2), and so Chromium was the only available public documentation. [As I've previously noted, the FIDO 2.2 spec lacks many details](https://github.com/kanidm/webauthn-rs/issues/259#issuecomment-1526847477), so caBLE implementations can only "do what Chromium does" (as I presume it to be the original implementation).

While this issue is still marked as "open", the code in `webauthn-authenticator-rs` works as both an authenticator and initiator, and has been for some time (mid-2023). There's even a basic caBLE tunnel server.

What remains is "future work ideas", things beyond the MVP.

Once I find a better way to organise these things in GitHub's issue tracker, I'll probably close this particular issue out.
